SELECT 'CREATE DATABASE {{ DB_DATABASE }}' 
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{{ DB_DATABASE }}')\gexec
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_user WHERE usename = '{{ DB_REPL_USER }}') THEN
        CREATE USER {{DB_REPL_USER}} WITH REPLICATION ENCRYPTED PASSWORD '{{ DB_REPL_PASSWORD }}'; 
    END IF; 
END $$;

ALTER USER {{DB_USER}} WITH PASSWORD '{{ DB_PASSWORD }}';

\c {{DB_DATABASE}}
CREATE TABLE IF NOT EXISTS emails (
    id SERIAL PRIMARY KEY,
    email VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS phonenumbers (
    id SERIAL PRIMARY KEY,
    number VARCHAR(20) NOT NULL
);

INSERT INTO Emails (email) VALUES ('test@test.ru');
INSERT INTO PhoneNumbers (number) VALUES ('+7 999 999 99 99');
